version: '3.8'
services:
  web:
    build:
      context: ./
    command: node index.js
#     volume:
#       - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3700:3700"
    # for debugging
    #entrypoint: ["sh", "-c", "2073600"]
